// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AlbUIClient is the client API for AlbUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlbUIClient interface {
	// ListEngineSpecs returns a list of Load Balancer Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (AlbUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type albUIClient struct {
	cc grpc.ClientConnInterface
}

func NewAlbUIClient(cc grpc.ClientConnInterface) AlbUIClient {
	return &albUIClient{cc}
}

func (c *albUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (AlbUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &AlbUI_ServiceDesc.Streams[0], "/v1.AlbUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &albUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AlbUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type albUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *albUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *albUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.AlbUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlbUIServer is the server API for AlbUI service.
// All implementations must embed UnimplementedAlbUIServer
// for forward compatibility
type AlbUIServer interface {
	// ListEngineSpecs returns a list of Load Balancer Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, AlbUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedAlbUIServer()
}

// UnimplementedAlbUIServer must be embedded to have forward compatible implementations.
type UnimplementedAlbUIServer struct {
}

func (UnimplementedAlbUIServer) ListEngineSpecs(*ListEngineSpecsRequest, AlbUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedAlbUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedAlbUIServer) mustEmbedUnimplementedAlbUIServer() {}

// UnsafeAlbUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlbUIServer will
// result in compilation errors.
type UnsafeAlbUIServer interface {
	mustEmbedUnimplementedAlbUIServer()
}

func RegisterAlbUIServer(s grpc.ServiceRegistrar, srv AlbUIServer) {
	s.RegisterService(&AlbUI_ServiceDesc, srv)
}

func _AlbUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AlbUIServer).ListEngineSpecs(m, &albUIListEngineSpecsServer{stream})
}

type AlbUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type albUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *albUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _AlbUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlbUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AlbUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlbUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AlbUI_ServiceDesc is the grpc.ServiceDesc for AlbUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlbUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.AlbUI",
	HandlerType: (*AlbUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _AlbUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _AlbUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "alb-ui.proto",
}
